{% set name = "transformer-smaller-training-vocab" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformer_smaller_training_vocab-{{ version }}.tar.gz
  sha256: 7843898842579fa80526bdd3a3696b55bdc7da4cfec095fbfa6b7153bf4ff972

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - transformers >=4.1.0,<5.0.0
    - pytorch >=1.8.0,<3.0.0,!=2.0.1
    - sentencepiece >=0.1.97,<0.2.0

test:
  imports:
    - transformer_smaller_training_vocab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/helpmefindaname/transformer-smaller-training-vocab
  summary: Temporary remove unused tokens during training to save ram and speed.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
