{% set name = "transformer-smaller-training-vocab" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformer_smaller_training_vocab-{{ version }}.tar.gz
  sha256: 8c7e589f338f797e81263656207418d7c81ea115a9060a6e96ac4eaa27b06d29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core
    - pip
  run:
    - python >=3.7
    - datasets ^2.0.0
    - transformers ^4.1extras
    - pytorch >=1.8.0<3.0.0
    - sentencepiece ^0.1.97

test:
  imports:
    - transformer_smaller_training_vocab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/helpmefindaname/transformer-smaller-training-vocab
  summary: Temporary remove unused tokens during training to save ram and speed.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
